version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/my_celery_app
hooks:
  AfterInstall:
    - location: scripts/setup.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ec2-user
