version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/my_celery_app

permissions:
  - object: /home/ec2-user/my_celery_app
    owner: ec2-user
    group: ec2-user
    mode: 0755
    type:
      - file
      - directory

hooks:
  AfterInstall:
    - location: scripts/setup.sh
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_celery_pm2.sh
      runas: ec2-user
  ValidateService:
    - location: scripts/validate.sh
      runas: ec2-user
