version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/my_celery_app

hooks:
  AfterInstall:
    - location: scripts/permissions.sh
      runas: root
    - location: scripts/setup.sh
      runas: ec2-user
    - location: scripts/start.sh
      runas: ec2-user
