version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/my_celery_app

permissions:
  - object: /home/ec2-user/my_celery_app
    owner: ec2-user
    group: ec2-user
    mode: "755"  # Changed from 0755 to "755" to prevent YAML misinterpretation
    type:
      - file
      - directory

hooks:
  BeforeInstall:
    - location: scripts/stop_celery_pm2.sh
      runas: root  # Run as root to have necessary permissions
  AfterInstall:
    - location: scripts/permissions.sh
      runas: root          # Changed from ec2-user to root
    - location: scripts/setup.sh
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_celery_pm2.sh
      runas: ec2-user
  ValidateService:
    - location: scripts/validate.sh
      runas: ec2-user
